services:
    fulgurio_image_handler.annotation:
        class: Fulgurio\ImageHandlerBundle\Metadata\Driver\AnnotationDriver
        arguments: [@annotation_reader]

    fulgurio_image_handler.image_listener:
        class: Fulgurio\ImageHandlerBundle\EventListener\ImageListener
        arguments :
            - @annotation_reader
            - @vich_uploader.property_mapping_factory
            - @service_container
        tags:
            - { name: kernel.event_subscriber }

#    fulgurio_image_handler.warmup:
#        class: Fulgurio\ImageHandlerBundle\CacheWarmer\ImageCacheWarmer
#        tags: [{name: kernel.cache_warmer}]
#        arguments: [@service_container]
